const LANG_MAP: Record<string, string> = {
  settings: "设置",
  model: "助手",
  "copy setting link": "复制设置链接",
  "are you sure to clear all history?": "清除所有记录，是否确认？",
  "clear history": "清除记录",
  new: "新话题",
  del: "消失",
  cut: "忽略",
  "please click above to set": "请点击上方进行设置",
  cost: "成本",
  stream: "动态回复",
  fetch: "静态回复",
  Tools: "工具",
  Clear: "清空",
  "saved api templates": "已保存的 API 脚本",
  "saved prompt templates": "已保存的提示自动回复",
  "no chat history here": "暂无对话记录",
  "This is a new chat session, start by typing a message":
    "这是一个新对话，开始输入消息",
  "Settings button located at the top right corner can be used to change the settings of this chat":
    "右上角的设置按钮可用于更改此对话的设置",
  "'New' button located at the top left corner can be used to create a new chat":
    "左上角的 '新' 按钮可用于创建新对话",
  "click above to change the settings of this chat":
    "点击上方更改此对话的参数",
  "click the NEW to create a new chat": "点击左上角 NEW 新建对话",
  "all chat history and settings are stored in the local browser":
    "所有对话保存在浏览器本地",
  "documents and source code are avaliable here":
    "详细文档与源代码可在此处获取",
  "generating...": "思考中，请保持网络稳定...",
  "re-generate": "重新思考",
  completion: "补全",
  "generated by": "思考助手: ",
  "info: chat history is too long, forget messages":
    "提示：对话太长超过了套餐限制，忽略了更早的内容",
  "warning: current chatstore version": "提示：聊天版本",
  retry: "重试",
  send: "发送",
  assistant: "助手消息",
  user: "用户消息",
  close: "关闭",
  "message copied to clipboard": "消息已复制",
  "total cost in this session": "本次会话总成本",
  "accumulated cost in all sessions": "所有会话总成本",
  export: "导出",
  "give this template a name:": "给此自动回复命名：",
  "no template name specified": "未指定自动回复名称",
  "as template": "保存为会话自动回复",
  "as api template": "保存为 API 脚本",
  "this will overwrite the current chat history! continue?":
    "将覆盖聊天！是否继续？",
  "please select a json file": "请选择一个 JSON 文件",
  "empty file": "提示: 空文件",
  "this is not an exported chatgpt-api-web chatstore file. the key 'chatgpt_api_web_version' is missing!":
    "此文件不符合要求，请检查是否正确",
  "import error on parsing json": "解析错误",
  version: "版本",
  "copied link:": "已复制：",
  reset: "重新开始",
  example: "示例",
  render: "渲染",
  "reset current": "清空聊天",
};

export default LANG_MAP;
